theme = "hugo-material"
baseurl = "/"
relativeurls = true
title = "The CodeMeta Project"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "\\.csv", "\\.R"]
publishDir = "../website"


[[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 1
[[menu.main]]
    name = "Crosswalk"
    url = "/crosswalk/"
    weight = 2
[[menu.main]]
    name = "Create"
    url = "/create/"
    weight = 3
[[menu.main]]
    name = "Terms"
    url = "/terms/"
    weight = 4
[[menu.main]]
    name = "User Guide"
    url = "/user-guide"
    weight = 5
[[menu.main]]
    name = "Developer Guide"
    url = "/developer-guide"
    weight = 6
[[menu.main]]
    name = "JSON-LD"
    url = "/jsonld"
    weight = 7
[[menu.main]]
    name = "Tools"
    url = "/tools"
    weight = 8


[params]
    name =  "codemeta"
    github =  "codemeta"
    custom_css = ["glyphicon.css"]
    #custom_css = ["cboettig.css"]
    repo = "codemeta.github.io"
    background = "img/pyramids.jpg"

    date_format = "Mon, Jan 2, 2006"
    description = "A Rosetta Stone for Software Metadata"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "json"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
